apply Dependency "nx-skip-elastic-agent-on-down-of-satellite-" for (parent_endpoint in get_object("Zone", host.zone).endpoints) to Service {
    parent_host_name = parent_endpoint

    // Disable active checks and notifications if parent endpoints are not UP
    states = [ Up ]
    disable_notifications = true
    disable_checks = true
    ignore_soft_states = true

    redundancy_group = "nx-skip-elastic-agent-on-down-of-satellite"

    // Targets all services with name Elastic Agent Status on Hosts that are not in Master Zone
    assign where service.name == "Elastic Agent Status"
    ignore where host.zone == "master"
}

apply Dependency "nx-disable-notifications-and-monitoring-on-elastic-agent-forwarder-disconnected" to Service {
    parent_host_name = host.vars.logmanager_forwarder_host
    parent_service_name = "Elastic Agent Status"

    // Disable active checks and notifications if parent service is not UP
    states = [ OK ]
    disable_checks = true
    disable_notifications = true
    ignore_soft_states = false

    assign where match("Elastic Ingest Status - *", service.name) && match("elastic-agent", host.vars.logmanager_log_source_type) && host.vars.nx_monitored_by_icinga_agent == true && host.vars.logmanager_forwarder_enable == true
}

apply Dependency "nx-disable-notifications-and-monitoring-on-elastic-agent-local-disconnected" to Service {
    parent_service_name = "Elastic Agent Status"

    // Disable active checks and notifications if parent service is not UP
    states = [ OK ]
    disable_checks = true
    disable_notifications = true
    ignore_soft_states = false

    assign where match("Elastic Ingest Status - *", service.name) && match("elastic-agent", host.vars.logmanager_log_source_type) && host.vars.nx_monitored_by_icinga_agent == true && host.vars.logmanager_forwarder_enable == false
}
